### ISSUE TITLE
Update task description to reflect new 0.4 API (both Java, Scala)

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/bigdataclass.org#5]

**Comment by vasia** [comment]
Hey! I would like to use the website exercises for an introduction-to-Stratosphere lab session. Should I go ahead and update the task descriptions or are you planning to make more changes?
Thanks!

**Comment by rmetzger** [comment]
Hey, very cool!

I think the new Java API is quite stable (and the exercises are not touching so many parts). So I'd be super happy if you could do that.
(The Scala API has not really changed from 0.4 to 0.5, we have not really updated Scala to 0.4 on Bigdataclass).

**Comment by StephanEwen** [comment]
Yes, great idea! Let us know if you encounter bugs or limitations!

BTW: We actually have a nice an future proof solution pending to the "multiple joins with solutionset" problem. The organizational solution was to find a another person with time and a fascination for such runtime stuff :-)
